### ISSUE TITLE
这个会持续维护吗？

### ISSUE THREAD

**Issue by jsRuner** [MyHdg0601/uniapp-vue2-hbx-starter#1]
是这样的，刚刚需要做一个小程序的，打算使用你这个脚手架，但是我看你整合的东西挺多，我还未能全部熟悉，担心后期有问题，无法找到人解决

**Comment by MyHdg0601** [comment]
你好，这个项目是会持续维护的，使用之前请先仔细阅读[文档](https://github.com/MyHdg0601/uniapp-vue2-hbx-starter/blob/main/README.md)，若有疑问可以提交issue或者[邮箱](mailto:HeDianGeng0601@outlook.com)联系我，后面如果使用人数多的话会考虑创建企鹅🐧群进行疑问解答。
